import React from 'react';
import Menu from '../menu/Menu';
import './Home.scss';
import {Link} from 'react-router-dom';

function Home() {

    return(       
        <div className="global">
            
            <div className="menuLink">
                
            </div>
        <div className="container">
                    
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
		<div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
        <div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
        <div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
        <div className="row">
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>
			<div className="hexagon"></div>{/* <!---16time)--> */}
		</div>
	</div>
    </div>
    );
}

export default Home;